# Copia para secrets.yaml (está no .gitignore) e preenche.
# Chave da API: openssl rand -base64 32
api_key: "COLOCA_AQUI_UMA_CHAVE_BASE64_DE_32_BYTES="
web_password: "muda-esta-password"
fallback_password: "muda-esta-password"

wifi_ssid_1: "Rede-principal"
wifi_password_1: "muda-esta-password"
wifi_ssid_2: "Rede-secundaria"
wifi_password_2: "muda-esta-password"
